services:
  postgis:
    image: postgis/postgis:17-3.5
    container_name: nest-map-postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_map
    ports:
      - '5433:5432'
    volumes:
      - postgis-data:/var/lib/postgresql/data
volumes:
  postgis-data:
